<?php require_once dirname(__FILE__).'/../../../data/version.php' ?>

- # symfony 1.4.16 で修正済み: http://trac.symfony-project.org/ticket/9970
  errno: E_WARNING
  errstr: "ob_start(): function '' not found or invalid function name"
  errfile: lib/vendor/symfony/lib/config/sfApplicationConfiguration.class.php
  errline: 155 # sfApplicationConfiguration::initConfiguration()

- # symfony 1.4.16 で修正済み: http://trac.symfony-project.org/ticket/9970
  errno: E_NOTICE
  errstr: "ob_start(): failed to create buffer"
  errfile: lib/vendor/symfony/lib/config/sfApplicationConfiguration.class.php
  errline: 155 # sfApplicationConfiguration::initConfiguration()

- # symfony 1.4.17 で修正済み: http://trac.symfony-project.org/ticket/9985
  errno: E_NOTICE
  errstr: "Array to string conversion"
  errfile: lib/vendor/symfony/lib/widget/sfWidgetFormSelectCheckbox.class.php
  errline: 105 # sfWidgetFormSelectCheckbox::formatChoices()

- # パッチ: https://github.com/rezzza/doctrine1/commit/0b838e2e5b2dcb055623e72258d9f4bdfca04f23
  errno: E_NOTICE
  errstr: "Array to string conversion"
  errfile: lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Abstract.php
  errline: 1152 # Doctrine_Query_Abstract::_getDqlCallbackComponents()

- # パッチ: https://github.com/LExpress/symfony1/commit/b90e1254f5208f8666491cf27392a22d38860131
  errno: E_DEPRECATED
  errstr: "preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead"
  errfile: lib/vendor/symfony/lib/util/sfToolkit.class.php
  errline: 362 # sfToolkit::pregtr()

- # パッチ: https://github.com/LExpress/symfony1/commit/b90e1254f5208f8666491cf27392a22d38860131
  errno: E_DEPRECATED
  errstr: "preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead"
  errfile: lib/vendor/symfony/lib/command/sfCommandManager.class.php
  errline: 111 # sfCommandManager::process()

- # パッチ: https://github.com/LExpress/symfony1/commit/b90e1254f5208f8666491cf27392a22d38860131
  errno: E_DEPRECATED
  errstr: "preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead"
  errfile: lib/vendor/symfony/lib/response/sfWebResponse.class.php
  errline: 409 # sfWebResponse::normalizeHeaderName()

- # パッチ: https://github.com/LExpress/symfony1/commit/b90e1254f5208f8666491cf27392a22d38860131
  errno: E_DEPRECATED
  errstr: "preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead"
  errfile: cache/<?php $user = posix_getpwuid(posix_getuid()); echo $user['name'] ?>/pc_frontend/test/config/config_core_compile.yml.php
  errline: ~ # sfWebResponse::normalizeHeaderName()

- # パッチ: https://github.com/LExpress/symfony1/commit/b90e1254f5208f8666491cf27392a22d38860131
  errno: E_DEPRECATED
  errstr: "preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead"
  errfile: lib/vendor/symfony/lib/vendor/lime/lime.php
<?php if (version_compare(OPENPNE_VERSION, '3.5.3', '<') || OPENPNE_VERSION === '3.9.0-dev'): ?>
  errline: [687, 688, 689, 690] # lime_output::echoln()
<?php else: ?>
  errline: [692, 693, 694, 695] # lime_output::echoln()
<?php endif ?>

- # 最新の Net_UserAgent_Mobile は PHP5 に移行されている: https://github.com/iteman/net-useragent-mobile/commit/48d42001ff7f235b8bb8bf5da844abb51b6daeff
  errno: E_DEPRECATED
  errstr: "Non-static method Net_UserAgent_Mobile::factory() should not be called statically, assuming $this from incompatible context"
  errfile: lib/util/opMobileUserAgent.class.php
  errline: 32 # opMobileUserAgent::__construct()

- # 最新の Net_UserAgent_Mobile は PHP5 に移行されている: https://github.com/iteman/net-useragent-mobile/commit/48d42001ff7f235b8bb8bf5da844abb51b6daeff
  errno: E_DEPRECATED
  errstr: "Non-static method Net_UserAgent_Mobile::isDoCoMo() should not be called statically, assuming $this from incompatible context"
  errfile: lib/vendor/PEAR/Net/UserAgent/Mobile.php
  errline: 144 # Net_UserAgent_Mobile::factory()

- # 最新の Net_UserAgent_Mobile は PHP5 に移行されている: https://github.com/iteman/net-useragent-mobile/commit/48d42001ff7f235b8bb8bf5da844abb51b6daeff
  errno: E_DEPRECATED
  errstr: "Non-static method Net_UserAgent_Mobile::isEZweb() should not be called statically, assuming $this from incompatible context"
  errfile: lib/vendor/PEAR/Net/UserAgent/Mobile.php
  errline: 146 # Net_UserAgent_Mobile::factory()

- # 最新の Net_UserAgent_Mobile は PHP5 に移行されている: https://github.com/iteman/net-useragent-mobile/commit/48d42001ff7f235b8bb8bf5da844abb51b6daeff
  errno: E_DEPRECATED
  errstr: "Non-static method Net_UserAgent_Mobile::isSoftBank() should not be called statically, assuming $this from incompatible context"
  errfile: lib/vendor/PEAR/Net/UserAgent/Mobile.php
  errline: 148 # Net_UserAgent_Mobile::factory()

- # 最新の Net_UserAgent_Mobile は PHP5 に移行されている: https://github.com/iteman/net-useragent-mobile/commit/48d42001ff7f235b8bb8bf5da844abb51b6daeff
  errno: E_DEPRECATED
  errstr: "Non-static method Net_UserAgent_Mobile::isWillcom() should not be called statically, assuming $this from incompatible context"
  errfile: lib/vendor/PEAR/Net/UserAgent/Mobile.php
  errline: 150 # Net_UserAgent_Mobile::factory()

- # 最新の Net_UserAgent_Mobile は PHP5 に移行されている: https://github.com/iteman/net-useragent-mobile/commit/48d42001ff7f235b8bb8bf5da844abb51b6daeff
  errno: E_DEPRECATED
  errstr: "Non-static method PEAR::staticPushErrorHandling() should not be called statically, assuming $this from incompatible context"
  errfile: lib/vendor/PEAR/Net/UserAgent/Mobile.php
  errline: 170 # Net_UserAgent_Mobile::factory()

- # 最新の Net_UserAgent_Mobile は PHP5 に移行されている: https://github.com/iteman/net-useragent-mobile/commit/48d42001ff7f235b8bb8bf5da844abb51b6daeff
  errno: E_DEPRECATED
  errstr: "Non-static method PEAR::isError() should not be called statically, assuming $this from incompatible context"
  errfile: lib/vendor/PEAR/Net/UserAgent/Mobile/Common.php
  errline: 140 # Net_UserAgent_Mobile_Common::Net_UserAgent_Mobile_Common()

- # 最新の Net_UserAgent_Mobile は PHP5 に移行されている: https://github.com/iteman/net-useragent-mobile/commit/48d42001ff7f235b8bb8bf5da844abb51b6daeff
  errno: E_DEPRECATED
  errstr: "Non-static method PEAR::staticPopErrorHandling() should not be called statically, assuming $this from incompatible context"
  errfile: lib/vendor/PEAR/Net/UserAgent/Mobile.php
  errline: 172 # Net_UserAgent_Mobile::factory()

- # 最新の Net_UserAgent_Mobile は PHP5 に移行されている: https://github.com/iteman/net-useragent-mobile/commit/48d42001ff7f235b8bb8bf5da844abb51b6daeff
  errno: E_DEPRECATED
  errstr: "Non-static method Net_UserAgent_Mobile::isError() should not be called statically, assuming $this from incompatible context"
  errfile: lib/vendor/PEAR/Net/UserAgent/Mobile.php
  errline: 174 # Net_UserAgent_Mobile::factory()

- # 最新の Net_UserAgent_Mobile は PHP5 に移行されている: https://github.com/iteman/net-useragent-mobile/commit/48d42001ff7f235b8bb8bf5da844abb51b6daeff
  errno: E_DEPRECATED
  errstr: "Non-static method Net_UserAgent_Mobile::isError() should not be called statically, assuming $this from incompatible context"
  errfile: lib/vendor/PEAR/Net/UserAgent/Mobile/DoCoMo.php
  errline: 605 # Net_UserAgent_Mobile_DoCoMo::parse()

- # 最新の Net_UserAgent_Mobile は PHP5 に移行されている: https://github.com/iteman/net-useragent-mobile/commit/48d42001ff7f235b8bb8bf5da844abb51b6daeff
  errno: E_DEPRECATED
  errstr: "Non-static method Net_UserAgent_Mobile::isError() should not be called statically, assuming $this from incompatible context"
  errfile: lib/vendor/PEAR/Net/UserAgent/Mobile/SoftBank.php
  errline: 215 # Net_UserAgent_Mobile_SoftBank::parse()

- # 最新の SimplePie では新しい構文に移行されている: https://github.com/simplepie/simplepie
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/simplepie/simplepie.inc
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Function split() is deprecated"
  errfile: lib/vendor/OAuth/OAuth.php
  errline: [720, 724] # OAuthUtil::parse_parameters()

-
  errno: E_STRICT
  errstr: "Non-static method Console_Getopt::doGetopt() should not be called statically"
  errfile: lib/vendor/PEAR/Console/Getopt.php
  errline: 68

-
  errno: E_STRICT
  errstr: "Non-static method PEAR::isError() should not be called statically"
  errfile: lib/vendor/PEAR/Console/Getopt.php
  errline: [87, 136]

-
  errno: E_STRICT
  errstr: "Non-static method Console_Getopt::_parseShortOption() should not be called statically"
  errfile: lib/vendor/PEAR/Console/Getopt.php
  errline: 135

-
  errno: E_STRICT
  errstr: "call_user_func_array() expects parameter 1 to be a valid callback, non-static method System::_removeTmpFiles() should not be called statically"
  errfile: lib/vendor/PEAR/PEAR.php
  errline: 808

-
  errno: E_STRICT
  errstr: "Non-static method Console_Getopt::getopt2() should not be called statically"
  errfile: lib/vendor/PEAR/System.php
  errline: 76

-
  errno: E_STRICT
  errstr: "Non-static method System::_dirToStruct() should not be called statically"
  errfile: lib/vendor/PEAR/System.php
  errline: 171

-
  errno: E_STRICT
  errstr: "Non-static method System::_parseArgs() should not be called statically"
  errfile: lib/vendor/PEAR/System.php
  errline: 193

-
  errno: E_STRICT
  errstr: "Non-static method PEAR::isError() should not be called statically"
  errfile: lib/vendor/PEAR/System.php
  errline: 194

-
  errno: E_STRICT
  errstr: "Non-static method System::_multipleToStruct() should not be called statically"
  errfile: lib/vendor/PEAR/System.php
  errline: 204

-
  errno: E_STRICT
  errstr: "Non-static method System::rm() should not be called statically"
  errfile: lib/vendor/PEAR/System.php
  errline: 440

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/ChannelFile.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/Common.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/Command.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/Config.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Function set_magic_quotes_runtime() is deprecated"
  errfile: lib/vendor/PEAR/PEAR/Config.php
  errline: [1026, 1033]

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/Dependency2.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/DependencyDB.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Function set_magic_quotes_runtime() is deprecated"
  errfile: lib/vendor/PEAR/PEAR/DependencyDB.php
  errline: [554, 581, 583, 558]

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/Downloader.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/Frontend.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/Installer.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/PackageFile/v2.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/PackageFile/v2/Validator.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/Registry.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Function set_magic_quotes_runtime() is deprecated"
  errfile: lib/vendor/PEAR/PEAR/Registry.php
  errline: [1140, 1144, 1179, 1183]

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/REST/10.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/PEAR/REST/11.php
  errline: ~

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/Calendar/Month/Weekdays.php
  errline: 132

-
  errno: E_DEPRECATED
  errstr: "Assigning the return value of new by reference is deprecated"
  errfile: lib/vendor/PEAR/Calendar/Calendar.php
  errline: 460

-
  errno: E_DEPRECATED
  errstr: "Non-static method Calendar_Engine_Factory::getEngine() should not be called statically, assuming $this from incompatible context"
  errfile: lib/vendor/PEAR/Calendar/Calendar.php
  errline: 210
